### PR TITLE
BigWarp Bdv Command

### PR DESCRIPTION
**Pull request by tischi**
Hi @bogovicj ,

I added a Command  (i.e. GUI) for opening two xml/hdf5 files to be aligned with BigWarp.
It seems to work:
https://github.com/tischi/bigwarp/blob/bdvUI/src/test/java/bigwarp/BigWarpBdvCommandTest.java#L7
Would that be something that you could merge?
It would be very useful for us.

### CODE REVIEW

**Comment by bogovicj** [comment]
Thanks @tischi! 
I'll have a look at it as soon as I can.

**Comment by bogovicj** [comment]
@tischi 
Not sure what's going on with Travis there, but this looks good. I'll merge now.

**Comment by tischi** [comment]
Great!
Since BigWarp is shipped with Fiji it could take a long time until the changes make it, or?
Or do you have an own update site?

**Comment by bogovicj** [comment]
Yea, it's shipped with Fiji, I don't have a bigwarp update site.

I will try to push the new version into fiji (relatively) quickly.
There are some other features / bug fixes I'd like to put into the next release.

**Comment by tischi** [comment]
How often is there a new Fiji release? Do you know?

**Comment by bogovicj** [comment]
Not sure, but it's possible to push a new version to fiji once its ready.

**Pull request merged**
