### PR TITLE
Save transform as xml

### PR DESCRIPTION
**Pull request by tischi**
Hi @bogovicj,

In this PR, with `Ctrl Shift E` you should be able to save an xml which has the BigWarp transform added. This is a very nice feature to have for big image data, because you do not need to touch the voxel data and still can view the transformed file in BDV.

### CODE REVIEW

**Comment by bogovicj** [comment]
@tischi , 
we can close  #77 when merging this right?

**Comment by tischi** [comment]
yes we can close #77

**Comment by bogovicj** [comment]
thanks @tischi

**Comment by bogovicj** [comment]
PS @tischi,
I added you as a contributor.  Is [this](https://github.com/saalfeldlab/bigwarp/blob/master/pom.xml#L78-L81) ok?
Specifically, is that User name for the imagej wiki okay?  ( I noticed that account edited pages for your stuff )

**Comment by tischi** [comment]
Thanks! The contribution name a.s.o. is fine!

**Pull request merged**
